Рабочая версия для сохранения коэффициента
javacore2017/lw2-1-iandreyshev pull request #1
Opened 2017-10-24 15:16 UTC by iandreyshev

Пока не выводится отчёт о проданных продуктах

2017-11-06 19:32 UTC, mrkurbatov requested changes
Просмотрите коменнтарии

2017-11-06 19:32 UTC, mrkurbatov commented on .idea/checkstyle-idea.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Папки .idea не должно быть в репозитории.

2017-11-06 19:32 UTC, mrkurbatov commented on src/main/java/ru/iandreyshev/supermarketSimulator/SupermarketSimulator.java
> +
Поля идут первыми в классе, потом методы

2017-11-06 19:32 UTC, mrkurbatov commented on src/main/java/ru/iandreyshev/supermarketSimulator/supermarket/Supermarket.java
> +    public void addProduct(SupermarketProduct product, Number amount) {
Почему супермаркет потомок кассы??

2017-11-06 19:32 UTC, mrkurbatov commented on src/main/java/ru/iandreyshev/supermarketSimulator/util/Logger.java
> +
Если хотите enum печатать как строку, то делайте так https://stackoverflow.com/a/2497532

2017-11-06 19:32 UTC, mrkurbatov commented on src/main/java/ru/iandreyshev/supermarketSimulator/SupermarketSimulator.java
> +        Number amount = takingProducts.getValue();
Для работы с деньгами используйте BigDecimal

2017-11-06 19:32 UTC, mrkurbatov commented on src/main/java/ru/iandreyshev/supermarketSimulator/SupermarketSimulator.java
> +        System.exit(EXIT_SUCCESS);
Зачем нужен код возврата из программы?

2017-11-06 19:32 UTC, mrkurbatov commented on src/main/java/ru/iandreyshev/supermarketSimulator/util/Logger.java
> +    public static void message(Date date, String message) {
Нужно ли передавать везде дату?

2017-11-06 19:32 UTC, mrkurbatov commented on src/main/java/ru/iandreyshev/supermarketSimulator/SupermarketSimulator.java
> +                    case ARRIVE:
Гораздо лучше использовать полиморфизм вместо свича

2017-11-06 19:32 UTC, mrkurbatov commented on src/main/java/ru/iandreyshev/supermarketSimulator/util/Logger.java
> +    public static final String EMPTY_AT_START =
Относительно дизайна класса Logger. Вместо кучи разных методов печати лучше использовать полиморфизм.
Например у вас есть метод log(LogEvent event). ProducLogEvent, SupermarketLogEvent наследники LogEvent в которых переопределен метод toString().

2017-11-06 19:32 UTC, mrkurbatov commented on src/main/java/ru/iandreyshev/supermarketSimulator/util/Rand.java
> +        if (min > max) {
Название метода не отражает суть

2017-11-07 04:02 UTC, iandreyshev commented on src/main/java/ru/iandreyshev/supermarketSimulator/util/Logger.java
> +
Исправил в случае PaymentType. В случае массы/ количества, мне кажется переводить нужно всё равно в классе Logget потому иначе строки будут неправильно использованы в предложении

2017-11-13 20:26 UTC, mrkurbatov approved these changes

2017-11-13 20:27 UTC, merged